---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
ratings:
  paths:
  - "**.md"
  - "**.js"
  - "**.vue"
  - "**.css"
  - "**.scss"
  - "package.json"
exclude_paths:
  - bin/
  - build/
  - config/
  - dist/
  - node_modules/
  - static/
  - tasks/
  - test/
