---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  stylelint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
  git-legal:
    enabled: true
ratings:
  paths:
  - "**.md"
  - "**.js"
  - "**.vue"
  - "**.css"
  - "**.scss"
  - "package.json"
  - "yarn.lock"
exclude_paths:
# - config/
- dist/
- node_modules/
- test/
- static/
