---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc.js
    checks:
      import/no-unresolved:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
ratings:
  paths:
  - "src/**.js"
  - "src/**.scss"
  - "app.js"
  - "webpack.config.babel.js"
exclude_paths:
- node_modules/
- test/
- tasks/
- build/
exclude_fingerprints:
- 6df301524c1b4d6cdd7dd5935cda768f
- ee47385f22344fc1029b0739ecc267eb
- 3f8f8f69d39d8e9df13f6b76a43b02c7
- 5343005665ed9f82fe1661a352aabb6e
