---
version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
exclude_paths:
  - bin/
  - build/
  - config/
  - coverage/
  - dist/
  - node_modules/
  - static/
  - test/
