---
engines:
  duplication:
    enabled: true
  metrics:
    enabled: true
  coverage:
    enabled: true
  stylelint:
    enabled: true
  eslint:
    enabled: true
exclude_paths:
  - dist/
  - node_modules/
  - test/
  - static/
  - config/
  - build/
