# replace default config

# multipass: true
# full: true

plugins:
  # - name
  #
  # or:
  # - name: false
  # - name: true
  #
  # or:
  # - name:
  #     param1: 1
  #     param2: 2
  - removeDoctype: true
  - removeXMLProcInst
  - removeComments
  - removeMetadata
  - removeXMLNS
  - removeEditorsNSData
  - cleanupAttrs: true
  - inlineStyles
  - minifyStyles: false
  - convertStyleToAttrs
  - cleanupIDs:
      remove: true
      minify: false
  - prefixIds
  - removeRasterImages
  - removeUselessDefs
  - cleanupNumericValues
  - cleanupListOfValues
  - convertColors: true
  - removeUnknownsAndDefaults
  - removeNonInheritableGroupAttrs
  - removeUselessStrokeAndFill
  - removeViewBox: false
  - cleanupEnableBackground
  - removeHiddenElems
  - removeEmptyText
  - convertShapeToPath
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - collapseGroups
  - convertPathData
  - convertTransform
  - removeEmptyAttrs
  - removeEmptyContainers
  - mergePaths
  - removeUnusedNS
  - sortAttrs
  - removeTitle: true
  - removeDesc: true
  - removeDimensions: true
  - removeAttrs
  - removeElementsByAttr
  - addClassesToSVGElement
  - removeStyleElement
  - removeScriptElement
  - addAttributesToSVGElement
