
language: node_js
node_js:
  - "node"
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn

env:
  - TEST_COMMAND="lint:js"
  - TEST_COMMAND="lint:scss"
  - TEST_COMMAND="test"

script:
  - (eval "yarn run $TEST_COMMAND")
