---
language: node_js
node_js:
  - node
dist: trusty
addons:
  chrome: stable
env:
  global:
    - NODE_ENV=test
before_install:
  - npm config set spin false
  - npm i -g http-server greenkeeper-lockfile@2
before_script:
  - greenkeeper-lockfile-update
  - export DISPLAY=:99.0
  - export CHROME_PATH="$(which google-chrome-stable)"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xvfb to boot
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm i -g coveralls
  - cat coverage/lcov.info | coveralls

script:
  - yarn test:unit
  - yarn test:e2e
  - yarn test:lighthouse
