---
language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
    - "packages/api-server/node_modules"
    - "$HOME/.nvm"
dist: trusty
addons:
  chrome: stable
before_install:
  - npm config set spin false
  - npm i -g http-server greenkeeper-lockfile@2
before_script:
  - greenkeeper-lockfile-update
  - yarn lerna bootstrap
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm i -g coveralls
  - cat coverage/lcov.info | coveralls
env:
  global:
    - JOBS=1
    - NODE_ENV=test
    - secure: c6gzNinL6AbKA/TKmMomcZRin4WvZTzcNTHYdwIbr2HNp/ofGXAPxqOkDL2wH3S87eBEDPYuMz1lp/Ky6JMDvPXJ8mXtbGOEEcGZvTtQISq9X2cqIqR928tTyEJw0n/v9sWzorL6I7/TPfXoi382QR/i9e4NRIJbvXCAeOVJq8uCHmF018vgup7tLmSCIFpwf91pnAya6NiHgCDLDQHqFYEJU0LygTIyHzUE8Aosss0jF4kkenvWZU8xPWTttLbjW6K80b8vezkwmEwa4wIbENaDVz8iQz24WRFzKPPEh296RsgJgS6NeNf6oG6OcU/J4bZxbqQNMMtNPVIBrefOtB7lZXrfqrCCuVTMlBcPVtcSfY3UWUfGGP+sXljmfi47d/AIgB3F36C7njP8gNtsdlpk+WJsuhrsm0aQ614zueEuYsEk+GElfr2cths7yxwDvEcQxEXGkWFxJ9cSdT76MZCVjt45MuBGmoiwcQ6CIb42PYOxxGRR2SXWVJTf9reP8EIysy+ylwcIpFAhIixS2QP1ffxN7/NYLgzE1TG+K+CVVrzKN/CKABMAHLFrpRXzicbM8a5e2xd/ULmDpcgQ5FyQddHbNQ8FU+YsPhIxUrv2NqCVI9LjGDt9FI9tzdzDzWux6VxZQBAqyt+EMURdXcB5y3MGS9QaH+BML7zPQz0=

script:
  - yarn lint:js
  - yarn lint:scss
  - yarn duplicate
  - yarn test:unit
  - yarn test:e2e

before_deploy:
  - heroku plugins:install heroku-cli-static
  - yarn build
after_deploy:
  - heroku static:deploy

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ccIjdCHvy7C7vH42cMuo51OWBaWoK2SOUfcmSWNj9sE/N8iwriKYFQNaD7umhJnojvrqwlQRnrriDGq9FCCKROne8So1n97JKFyCPBRjCI9aH7nsdjl4T5F10SvmF0ZMBf4cXGR+sX5HQrJqFtwzq4HADO2bhKodLWNTknwJSoNn96JEhi1bmOY2/Bl+dvdu+yggbT7mHaZzaWSXJbG5bjS4ssVQZ24EZ2lHviA0kB2X90FPo+7bLpUnKh34LNOAXNk3AG6a+EgthXOfrUU/QsFe+sW+oQdHigteAB0ZwGnoVOdO+hsy1CCZ8njWiqJxpB7hdP/IBEcSBMyDZt2+TNhWJbrcAILIOLmN3rVAxxvvvQXjVuJ/BuC6B/VX0SM7ekwhljb/lj1A+KOtSFli58s85ZmSyArBkG+3gCfz6PCwp8qipIJpoUoo7mCqRBX3Wi0fNyy/3L+HpqrlBC3uJOPxHGTa8TW2HvjzuqzoYqw62kceRGQg6UNkQyVjB/ePRK2UN4/5WKv/nrwlzqi3VJPkVTuJGmg6qIls6uvghlBtYHVe4pjAuX50T9KpKwuFW0gYKILbCFNmqJGwKBC/TrmP99dZJaokOGUc3tdmENkcv68CiJ/87Aon+mOF9lwGlk2A9mkJC7ujCZbfRW7q1v14O1l/q//fAJk4HsHL0Y0=
  app:
    master: three-one-two-staging
