---
language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.nvm"
dist: trusty
addons:
  chrome: stable

# hooks
before_install:
  - openssl aes-256-cbc -K $encrypted_76951814e78d_key -iv $encrypted_76951814e78d_iv -in .env.enc -out .env -d
  - npm config set spin false

# env vars
env:
  global:
    - JOBS=1
    - NODE_ENV=test

# build jobs
jobs:
  include:
    # precache npm packages
    - stage: precache
      script: true
    # lint src
    - stage: linting
      script: yarn lint:js
      name: "Lint JS"
    - script: yarn lint:scss
      name: "Lint SCSS"
    - script: yarn lint:md
      name: "Lint Markdown"
    # run tests
    - stage: tests
      script: yarn test:unit
      name: "Unit Tests"
    - script: yarn test:e2e
      name: "Integration Tests"
      before_install:
        - npm i -g http-server
    # deploy scripts
    - stage: deploy
      name: "Deploy API Server"
      script: skip
      deploy:
        provider: script # Run a custom deployment script which we will define below
        script: bin/deploy api
        skip_cleanup: true
        on:
          all_branches: true
          master: false
