---
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.cache/yarn
    - node_modules
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
addons:
  code_climate:
    repo_token: 6e1412ae6fabced67e91bdef69c326e9d1d10080e65fc2ffc2ddaa33e5492194
branches:
  only:
  - master
  - develop

before_install:
  - git config --global url."https://".insteadOf git+https://
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
after_script:
  - yarn run killpm2
