---
sudo: false
language: node_js
node_js:
  - v7
  - v6
  - v5
  - v4
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
addons:
  apt:
    packages:
      - xvfb
