---
sudo: false
language: node_js
node_js:
  - 7
  - 6
  - 5
  - 4
  - '0.12'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  directories:
    - $HOME/.cache/yarn
    - node_modules
addons:
  code_climate:
    repo_token: 6e1412ae6fabced67e91bdef69c326e9d1d10080e65fc2ffc2ddaa33e5492194
