---
language: node_js
node_js:
  - node
cache:
  yarn: true
dist: trusty
addons:
  chrome: stable
before_install:
  - npm config set spin false

env:
  global:
    - JOBS=1
    - NODE_ENV=test

jobs:
  include:
    - stage: linting
      script: yarn lint:js
    - script: yarn lint:scss
    - script: yarn lint:md
    - stage: compile
      script: yarn build
    - stage: tests
      script: yarn test
