
language: node_js
node_js:
  - "node"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
dist: trusty
addons:
  chrome: stable
install:
  - yarn

env:
  - TEST_COMMAND="yarn run unit"
  - TEST_COMMAND="yarn run integration"
  # - TEST_COMMAND="yarn run accessibility"

script:
  - (eval "$TEST_COMMAND")
