---
language: node_js
node_js:
  - node
cache:
  yarn: true
dist: trusty
addons:
  chrome: stable
before_install:
  - npm config set spin false

env:
  global:
    - JOBS=1
    - NODE_ENV=test

before_script:
  - yarn build

jobs:
  include:
    - stage: linting
      script: yarn lint:js
    - script: yarn lint:scss
    - stage: tests
      script: yarn test
