
language: node_js
node_js:
  - "node"
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn

env:
  - TEST_COMMAND="yarn run lint:js"
  - TEST_COMMAND="yarn run lint:scss"
  - TEST_COMMAND="yarn run unit"
  - TEST_COMMAND="yarn run e2e"

script:
  - (eval "$TEST_COMMAND")
