
language: node_js
node_js:
  - "node"
sudo: false
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - node_modules
dist: trusty
addons:
  chrome: stable
before_install:
  - npm config set spin false

env:
  global:
    - JOBS=1
    - NODE_ENV=test

jobs:
  include:
    - stage: tests
      script: yarn run unit
    - script: yarn run integration
    - stage: build script
      script: yarn run build
    - stage: test staging
      script: 'curl https://three-one-two-staging.herokuapp.com/#/'
      if: branch = develop
    - stage: test production
      script: 'curl https://312development.com/#/'
      if: branch = master
