site_name: 312 Development
site_url: https://nielse63.github.io/312-development
repo_url: https://git.enova.com/nielse63/312-development
theme:
  name: 'material'
pages:
  - Home: index.md
  - Motivation: motivation.md
  - Setup: setup.md
  - Dependencies: dependencies.md
  - CLI Commands: cli-commands.md
  - Development: development.md
  - Code Quality: code-quality.md
  - Testing: testing.md
  - Documentation: documentation.md
  - Third-Party Integrations: third-party-integrations.md
  - Deployment: deployment.md
  - Acknowledgements: acknowledgements.md
